sudo : required
services: 
  - docker

before_install:
  - docker build -t tomna/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tomna/docker-react npm run test -- --coverage





